name: DisplayModule Build Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup PlatformIO
        run: |
          pip install platformio

      - name: Build firmware
        run: |
          cd DisplayModule
          pio run